# Generated by Django 5.2.6 on 2025-10-22 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del usuario', max_length=100)),
                ('apellido', models.CharField(help_text='Apellido del usuario', max_length=100)),
                ('email', models.EmailField(help_text='Correo electrónico del usuario', max_length=255)),
                ('contrasena', models.CharField(help_text='Contraseña del usuario', max_length=255)),
                ('saldo', models.DecimalField(decimal_places=2, help_text='Saldo disponible del usuario', max_digits=15)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el usuario está activo')),
                ('foto', models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='img_usuarios/')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id_portafolio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_port', models.CharField(help_text='Nombre del portafolio', max_length=100)),
                ('fecha', models.DateField(help_text='Fecha de creación del portafolio')),
                ('descripcion', models.TextField(help_text='Descripción del portafolio')),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total del portafolio', max_digits=15)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portafolios', to='app_Usuario.usuario')),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
            },
        ),
    ]
